ebs-init: Wait for EBS volume to appear and idempotently mount it.

diff --git a/provisioners/shell/ebs/ebs-init b/provisioners/shell/ebs/ebs-init
--- a/provisioners/shell/ebs/ebs-init
+++ b/provisioners/shell/ebs/ebs-init
@@ -6,6 +6,10 @@ set -e
 
 readonly SCRIPT_NAME="$(basename "$0")"
 
+# Max wait time is 300s
+readonly WAIT_MAX_RETRIES=60
+readonly WAIT_SLEEP_INTERVAL=5
+
 # =============================================================================
 
 function print_usage {
@@ -66,6 +70,30 @@ function assert_running_as_root {
   fi
 }
 
+# Wait for the EBS volume to appear,
+# because it may not be attached to the EC2 instance at launch
+function wait_volume {
+  local readonly device_name="$1"
+  for (( i=1; i<="$WAIT_MAX_RETRIES"; i++ )); do
+    # Use -e not -f, because $device_name may be a symbolic link
+    if [[ -e "$device_name" ]]; then
+      if [[ -b "$device_name" ]]; then
+        log_info "Found EBS volume $device_name"
+        return
+      else
+        log_error "$device_name is not a block device."
+        exit 1
+      fi
+    else
+      log_warn "No EBS volume at $device_name, will sleep for $WAIT_SLEEP_INTERVAL seconds and try again."
+      sleep "$WAIT_SLEEP_INTERVAL"
+    fi
+  done
+
+  log_error "Could not find EBS volume $device_name after $WAIT_MAX_RETRIES retries."
+  exit 1
+}
+
 function format_volume {
   local readonly device_name="$1"
   local readonly device_fs=$(lsblk -f -n -o fstype $device_name)
@@ -83,10 +111,14 @@ function mount_volume {
   local readonly device_name="$1"
   local readonly device_fs="$2"
   local readonly mount_point="$3"
-  log_info "Mounting $device_fs volume $device_name to $mount_point"
   mkdir -p "$mount_point"
-  echo "$device_name $mount_point $device_fs defaults 0 0" | tee -a /etc/fstab
-  mount -a
+  if  ! grep -q "^$device_name" /etc/fstab ; then
+    log_info "Mounting $device_fs volume $device_name to $mount_point"
+    echo "$device_name $mount_point $device_fs defaults,nofail 0 0" | tee -a /etc/fstab
+    mount -a
+  else
+    log_info "$device_name already in /etc/fstab, keeping it that way."
+  fi
 }
 
 # =============================================================================
@@ -126,6 +158,7 @@ function run {
 
   assert_running_as_root
 
+  wait_volume "$device_name"
   local readonly device_fs=$(format_volume "$device_name")
   mount_volume "$device_name" "$device_fs" "$mount_point"
 }
